### PR TITLE
Multiple Menu Fixes

### LINKED ISSUE #116: Checkmark menu items do not work.
**Description**
A menu item of the type "checkmark" does not behave like it does in electrons menu-bar. 
And when trying to build the expected behavior with the custom-electron-titlebar, it results in interference with electrons functionalities.

**To Reproduce**
Minimal example showing the issues is provided at the end.

**About rebuilding the expected behavior**
When a click-handler, to toggle the checkmark manually, is added (in the example provided as a comment), electrons default behaviour does not work anymore, because now the checkmark gets toggled twice.  
This may be ok in some use cases, because the default electron menu bar is hidden. But: The accelerators still seem to execute electrons default behavior.  
This results in the `click` function with the desired action being executed, but the checkmark still displaying its previous state.
So after a long time of debugging and searching for the problem, my current solution is to store the checkmark's state in the data model and manually set it from there, which I want to change as soon as possible. Also I am having issues when one checkmark influences a different checkmark: Because the submenus of submenus from the custom-electron-titlebar do not close after being clicked, a wrong state is shown, as only the clicked menu item gets updated and the other one changes its checkmark state only after the (sub)menu is being reopened.

**Expected behavior**
When clicking on a checkmark menu item, its `.checked` value should be inverted and the checkmark should appear or disappear.

**Screenshots**
image

**Desktop:**
 - OS: Windows 10
 - Electron version 1.7.16
 - Node Version 7.9.0
 - Custom-electron-titlebar version: 3.2.5

**renderer.js**
```js
const { Titlebar } = require('custom-electron-titlebar');
new Titlebar();
```
**main.js**
```js
const {app, BrowserWindow, Menu} = require('electron')
const path = require('path')
let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({webPreferences: {enableRemoteModule: true}})
  mainWindow.loadURL(path.join(__dirname, 'index.html'))
  mainWindow.on('closed', function () {mainWindow = null})
  Menu.setApplicationMenu(Menu.buildFromTemplate([{
    label: 'Menu',
    submenu: [{
      label: 'Toggle Me!',
      type: 'checkbox',
      // Toggle the checkmark manually:
      // click: o => o.checked = !o.checked,
      accelerator: "T"
    }]
  }]))
}

app.on('ready', createWindow)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
app.on('activate', () => {
  if (mainWindow === null) createWindow()
})
```

### LINKED ISSUE #124: Submenu appears with a scrollbar
**Describe the bug**

See the gif below

Isw7jdT9vI

When you open a submenu, the menu appear at right but in a scrollbar (possible overflow problem)

**To Reproduce**
1. Disable all application css
2. Open a submenu

You can use my project [PCA - branch 79-titlebar](https://github.com/Kiyozz/papyrus-compiler-app/tree/79-titlebar) using pnpm, `pnpm i --shamefully-hoist`, `pnpm dev` (node@^14.15)

**Expected behavior**
Submenu appear next to the menu item

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Electron version 11.2.0
 - Node Version 12.18.4 (node version from electron 11.2.0)

### LINKED ISSUE #133: menu roles not working (electron 11.2.3)
The built in roles from electron Menu don't work when clicked through the custom-electron-titlebar, but they do on the native electron Menu.

I've tried reload, forceReload, zoomIn, zoomOut, copy, selectAll, quit, about
no roles seem to work at all on custom-electron-titlebar

edit: if I manually set a click() event on the menuItem, that works fine, it's just the roles that have trouble.

 - OS:  Windows 10 64bits
 - Electron v11.2.3
 - Node v10.23.0

### PR DESCRIPTION
**Pull request by Araxeus**
I'll start with saying I love the idea of this lib, but I faced some problems while using it, that I fixed in my program awhile ago
But I decided I should probably also share some fixes on the original source.

### The Initial Problems:
* Submenu's not showing at all (because `.menubar-menu-container` CSS property `overflow-y` wasn't set to `visible`)
* Clicking on a `checkbox` looked like it didn't do anything (it was setting `item.checked = !item.checked` twice)
* Radio buttons located in a submenu wouldn't dynamically update visually
* Submenu items wouldn't close on click
* Menu Items with roles **didn't work at all**
* `titlebar.updateMenu(null || undefined)` throws an error but works (dispose of current menu)

### The Fixes :
* 9dc885f 
   Set menu-container internal css to `overflow-y: visible;`. fix #124 
   
* 5e17933
   Fixes checkbox's being triggered twice. fix #116 (First trigger is in [electron/menu-item.ts](https://github.com/electron/electron/blob/master/lib/browser/api/menu-item.ts#L47-L52))
   
* a7cfa0a / 918e8e6 
   inherit `closeSubmenu()` in `Submenu` class allows submenus to close when their content is clicked
   That fix items in submenu's not closing on click

* da8999c
   Following the last change, submenu will close only if item type isn't `checkbox` or `radio` which allows them to work as before

* 76b0726
 Fixes menu roles by emulating the accelerator shortcut buttonDown when menuitem  is clicked. fix #133
abit of a hacky way but I think its way better than the ipc method that didn't even work

* e4a5df1
 Dynamically visually update radio button groups by passing menuContainer to `CETMenuItem` and updating all radio buttons in the menuContainer when `CETMenuItem.click()` is called and `type === radio`

* 0e61412
  if `menu` in `titlebar.updateMenu(menu)` is `null || undefined` , dispose of menu and exit function to avoid errors

#### Would love feedback on this if there is any :)

 <details>
  <summary> Click to view sample menu template for testing</summary>

```javascript
  const template = [
    {
      label: "Options",
      submenu: [
        {
          label: "zoomIn",
          role: "zoomIn"
        },
        {
          label: "zoomOut",
          role: "zoomOut"
        },
        {
          label: "Radio1",
          type: "radio",
          checked: true
        },
        {
          label: "Radio2",
          type: "radio",
        },
        {
          label: "Checkbox1",
          type: "checkbox",
          checked: true,
          click: (item) => {
            console.log("item is checked? "+item.checked);
          }
        },
        {
          label: "Checkbox2",
          type: "checkbox",
          checked: false,
          click: (item) => {
            console.log("item is checked? "+item.checked);
          }
        },
        {
          label: "Radio Test",
          submenu: [
            {
              label: "Sample Checkbox",
              type: "checkbox",
              checked: true
            },
            {
              label: "Radio1",
              checked: true,
              type: "radio"
            },
            {
              label: "Radio2",
              type: "radio"
            },
            {
              label: "Radio3",
              type: "radio"
            }
          ]
        },
        {
          label: "Quit",
          click: ()=>{app.quit()}
        },
      ]
    }
  ];
  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
```
</details>

---- 

Also, why is this git repo not actually the same version as the npm package? (3.2.5 vs 3.2.6)
It also has an src folder instead of lib, which means that when cloning the repo you don't have access to all files
and running `dev` will result in an error because of `lib` folder missing which is abit weird 😅

### CODE REVIEW

**Comment by ericblade** [comment]
> It also has an src folder instead of lib, which means that cloning the repo and running dev will run an error because of lib folder missing which is abit weird

source belongs in repos, build data belongs in releases, and never the two shall meet except in dev repos and build servers. :-)

(at least, that's my personal take on it)

code changes look good, although i don't know where the duplicate checkbox toggling thing is.  i don't know anything about the menu stuff actually, don't use it in my own instance at all.. but it looks good at a glance to me

**Comment by Araxeus** [comment]
@ericblade  
That was the duplicate checkbox
https://github.com/AlexTorresSk/custom-electron-titlebar/blob/04b3e09e0f122ebe5c11db0fcdbb36b8995cd533/src/menu/menuitem.ts#L141-L144
Of files that aren't even in this git (You see the problem ?)
check out `custom-electron-titlebar\lib\vs\base\common\actions.js`
these file automates the status of checkbox's on click and that's why it was proccing twice
(These file is also the one responsible for making radio buttons work as intented)

**Comment by timlg07** [comment]
Yes, the checkbox toggled twice would explain #116. I would love to see your changes merged, they are looking great.

**Comment by ericblade** [comment]
> That was the duplicate checkbox

I see where you removed one, I was just curious where the other one is, since you said it was getting triggered twice, and that's not in the changelog, since you didn't touch it :-)

> The original menuitem actions file isn't even in this git, only in release (You see the problem with repo not having the same version as release ??)

a repo might collect many changes before a release is made... 

Above, I was addressing your concern about the src not being in the release, and the lib not being in the src, which is imo, something that should never occur.  A repo collecting changes before a release is highly dependent on the maintainers, though.  I personally advocate for an automatic release generator that will always package up master branch whenever there's a change and make a release.  A lot of people haven't got to setting that sort of thing up though.  I haven't even got it close to working the way I'd like it to, on even any of my bigger repos.

**Comment by ericblade** [comment]
Anyway! LGTM, also 👍

**Comment by AlexTorresSk** [comment]
Hello everybody.

Thanks guys for always being on the lookout for updates and bugs from the library. I haven't really had time to publish the 3.2.6 changes to npm.
On the other hand, when I developed this library, I did not have the complete knowledge of releases, versioning, among others; therefore there is a lib folder which is actually the build folder for the entire project 🤭.
As soon as I have time I will dedicate myself to cleaning and debugging the code.

Thanks again for your support.

**Comment by Araxeus** [comment]
@AlexTorresSk 
You should know that this pull request was tested one 3.2.6, 
So it should be easy to implement into npm :)

**Comment by Araxeus** [comment]
@AlexTorresSk 
I updated and fixed typescript compile error that I missed (sorry about that 😅)
also changed radio buttons to dynamically visually update on click (by passing over all radio buttons in the same group)

Would love to know if there is any kind of ETA on publishing those changes :)

**Comment by Araxeus** [comment]
@ericblade 
My last answer on why the checkbox got updated twice was wrong. this is my new working theory:

I think checkbox + radio status internally works as usual when this.item.click() is called,
but not updated visually until `this.updateChecked()` OR `this.updateRadioGroup()` OR submenu is closed and re-opened
(and that's because this.item isn't rendered again unless the whole submenu gets re-rendered)

So `CETMenuItem.onclick()` was calling `item.click()` (first checkbox change) and then `item.checked = !item.checked` (second change)

**Pull request merged**
