### PR TITLE
v4.1.0

### LINKED ISSUE #149: checkbox icon and radio icon are the same
Currently both `checkbox` and `radio` menu items render the same icon when checked

Would be nice to change radio button checked icon to a circle checkmark instead of a tick checkmark.

### LINKED ISSUE #174: Default Parameters For onMinimize, onMaximize, etc.
**Describe the bug**
I'm a little confused about why this is an issue, considering that older releases of custom-electron-titlebar did not require developers to write out the code to make the titlebar buttons work in the normal, standard way. However, in v4.0.1, I can't leave parameters like onMinimize and onMaximize blank without errors.
I'm not too familiar with TypeScript, but the parameters should default to the following:
```
    onMinimize: function() { BrowserWindow.getFocusedWindow().minimize(); },
    onMaximize: function() { BrowserWindow.getFocusedWindow().isMaximized()?BrowserWindow.getFocusedWindow().unmaximize():BrowserWindow.getFocusedWindow().maximize(); },
    onClose: function() { BrowserWindow.getFocusedWindow().close() },
    isMaximized: function() { return BrowserWindow.getFocusedWindow().isMaximized() },
    onMenuItemClick: function() { console.log("nothing"); }
```

**To Reproduce**
```
var titlebar = new customTitlebar.Titlebar({
	backgroundColor: customTitlebar.Color.fromHex("#474747"),
    menu: null
}); // used to work - no longer does
```

**Expected behavior**
custom-electron-titlebar will know that since onMinimize, onMaximize, etc. were left blank, it should make the default buttons.

**Desktop (please complete the following information):**
 - OS: Windows
 - Electron version 11.1.1
 - Node Version 14.16.0

### PR DESCRIPTION
**Pull request by Araxeus**
Lots of fixes and improvements, its too late at night right to detail everything now but in short:

* Fix submenu's [[1](#note1)] 

* Fix Checkboxes/Radio buttons [[1](#note1)] 

* Added [radio icons](https://user-images.githubusercontent.com/78568641/152664791-ce11be4e-355e-4560-9acf-423178e3163d.png) (fix #149) [[1](#note1)] 

* Allow changing svg icon color

* Added refreshMenu() function (automatically pulls new menu from `Menu.getApplicationMenu()`)

* Reduce 99% of the boilerplate from the last release (fix #174)

* menuOptions.menu can be set to `null` to not use any menu or `undefined` (can just omit the property) to automatically get it from `Menu.getApplicationMenu()`)

* Fix controls button svg out of position when browserWindow height is low

and probably more, will try to find time to write more details about this pr /+ add docs later this week

Notes:

* example menu was changed because default electron menu isn't enough for testing - need to test that custom menu with submenu+checkbox+radio+separator+role works

* [1] <a name="note1"> easy way to experience the submenu/radioButton **fixes**: try loading the example menu in v4.0.1 - it wont work at all

* All fixes and improvements were also tested on https://github.com/th-ch/youtube-music/pull/596

## TODO - add empty checkbox icon (unchecked box)

### CODE REVIEW

**Comment by AlexTorresSk** [comment]
This is fantastic. But remember that the changes go through the develop branch first.
Please do the PR to the develop branch to avoid conflicts.

**Comment by Araxeus** [comment]
Roger that

**Comment by AlexTorresSk** [comment]
@Araxeus 
I merged this into develop, since I had done some previous commits it looks like a weird merge, but everything is merged and up to date.

On the other hand, I can create the documentation for the new implementation on the Wiki, and thus you save doing this.

**Comment by Araxeus** [comment]
Ok great this needs alot of wiki changes, would be nice if you could make it a PR so that I can also have a look and confirm that all the changes are present 

should includes:
* { setupTitlebar, attachTitlebarToWindow }` 
* `titlebar.refreshMenu()`
*  `options.svgColor`
*  and how to use/not use a menu )

(also need to add to wiki alot of things that already existed in readme.md before - see #168)

**Comment by Araxeus** [comment]
@AlexTorresSk any eta on when a new version will be published?

**Pull request merged**
